Added json summary

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -4,9 +4,6 @@ on:
   push:
     branches:
       - main
-  pull_request:
-    branches:
-      - main
 
 jobs:
   test:
@@ -50,8 +47,16 @@ jobs:
       # Fetch coverage report (adjust path if needed)
       - name: Fetch coverage report
         run: |
+          if [ ! -f ./coverage/coverage-summary.json ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
+
+          echo "Coverage report found"
+
           COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
           echo "Test coverage is ${COVERAGE}%"
+
           if (( $(echo "$COVERAGE < 85" | bc -l) )); then
             echo "Test coverage is below 85%, cannot merge."
             exit 1
@@ -59,6 +64,10 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: check-coverage
+    permissions:
+      contents: read
+      pages: write
+      id-token: write
 
     steps:
       - uses: actions/checkout@v4
